[main]
api_key = ""
access_token = ""

[sender]
offline_mode = false
output_dir = "/tmp/tasks"
api_url = ""
download_url_prefix = "http://download"
is_public = true
is_verified = true
generate_md5 = false